### ISSUE TITLE
Discuss database schema

### ISSUE THREAD

**Issue by drholmie** [scalableinternetservices/TeamPhelps#1]
Discuss the database schemas of all the user stories/ features discussed in #2 . 
Questions to answer:
- How many resources do we have? 
- What CRUD operations do we support?
- How many parent/foreign key relations exist? Which resources need polymorphism?

Ideally this will result in a database schema diagram to refer to during development. 

Feel free to continue the discussion on things missed out above.

**Comment by kimiaf1998** [comment]
Post:
We have Create/Read/Update/Delete (all operations)

Post table features:

- post type
- tags (folders)
- title
- body
- posting options

- The owner of the post and instructors and TAs have full access to CRUD operations on a post.
